Commit Technologies.md
mik-moo/Read_between_the_wines pull request #1
Opened 2022-09-25 21:34 UTC by aotreaux

For the database section, we will utilize an ERD (Entity Relationship Diagram) in addition to pgAdmin 4 within SQL.

2022-09-25 22:04 UTC, mik-moo requested changes
Update ML and DB once we look at those files

2022-09-25 22:41 UTC, MLGood1 requested changes
In the machine learning portion, our training a unsupervised learning model with a K-means clustering algorithm

2022-09-26 20:31 UTC, Fakparu approved these changes

2022-09-26 20:33 UTC, mik-moo approved these changes

2022-09-26 20:35 UTC, mik-moo approved these changes

2022-10-15 17:26 UTC, merged